---
- name: Apply All Updates
  yum: name=* state=latest

- name: install util
  yum: name={{item}} state=latest
  with_items:
  - "gcc"
  - "make"
  - "telnet"
  - "wget"
  - "tcpdump"
  - "sysstat"
  - "nmap"
  - "git"
  - "openssl-devel"
  - "vim-enhanced"
  - "python-devel"
  - "python-setuptools"
  - "curl"
  - "curl-devel"
  - "unzip"

- name: Install pip
  easy_install: name=pip state=latest

- name: Install aws-tools
  pip: name={{item}} state=latest
  with_items:
  - awscli
  - aws-shell

- name: "/etc/cloud/cloud.cfg"
  lineinfile: 'dest=/etc/cloud/cloud.cfg line="locale: {{locale}}"'
- name: set repo_upgrade to /etc/cloud/cloud.cfg
  lineinfile: 'dest=/etc/cloud/cloud.cfg regexp="repo_upgrade\:" line="repo_upgrade: {{repo_upgrade}}"'
- name: "/etc/sysconfig/i18n"
  replace: >
    dest=/etc/sysconfig/i18n
    regexp='^LANG=en_US\.UTF-8'
    replace='LANG={{locale}}'
- name: "/etc/sysconfig/clock"
  replace: >
    dest=/etc/sysconfig/clock
    regexp='^ZONE=\"UTC\"'
    replace='ZONE="{{zone}}"'
- name: "/etc/localtime"
  file: >
    src={{zoneinfo_path}}
    dest=/etc/localtime
    state=link
    force=yes